/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package main;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.stage.Stage;
import model.*;
import view.*;

public class App extends Application {
    public static void main(String[] args) {
        launch(args);
    }

    @Override
    public void start(Stage primaryStage) throws Exception {
        Engine engine;
        String param;

        try {
            param = getParameters().getUnnamed().get(0);
        } catch (Exception e) {
            param = "online";
        }


        if (param.equalsIgnoreCase("online")) {
            engine = new OnlineEngine();
        } else if (param.equalsIgnoreCase("offline")) {
            engine = new OfflineEngine();
        } else {
            System.out.println("Invalid argument");
            engine = null;
            System.exit(1);
        }

        Window window = new Window(engine);

        primaryStage.setTitle("Space Traders");
        primaryStage.setScene(window.getScene());
        primaryStage.show();
    }
}
